# Generated by Django 4.0.4 on 2022-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
